// Copyright 2019 IBM Corp
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureContainer) DeepCopyInto(out *SecureContainer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	in.Object.DeepCopyInto(&out.Object)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureContainer.
func (in *SecureContainer) DeepCopy() *SecureContainer {
	if in == nil {
		return nil
	}
	out := new(SecureContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecureContainer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureContainerImage) DeepCopyInto(out *SecureContainerImage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureContainerImage.
func (in *SecureContainerImage) DeepCopy() *SecureContainerImage {
	if in == nil {
		return nil
	}
	out := new(SecureContainerImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecureContainerImage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureContainerImageConfig) DeepCopyInto(out *SecureContainerImageConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureContainerImageConfig.
func (in *SecureContainerImageConfig) DeepCopy() *SecureContainerImageConfig {
	if in == nil {
		return nil
	}
	out := new(SecureContainerImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecureContainerImageConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureContainerImageConfigList) DeepCopyInto(out *SecureContainerImageConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecureContainerImageConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureContainerImageConfigList.
func (in *SecureContainerImageConfigList) DeepCopy() *SecureContainerImageConfigList {
	if in == nil {
		return nil
	}
	out := new(SecureContainerImageConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecureContainerImageConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureContainerImageConfigRef) DeepCopyInto(out *SecureContainerImageConfigRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureContainerImageConfigRef.
func (in *SecureContainerImageConfigRef) DeepCopy() *SecureContainerImageConfigRef {
	if in == nil {
		return nil
	}
	out := new(SecureContainerImageConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureContainerImageConfigSpec) DeepCopyInto(out *SecureContainerImageConfigSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureContainerImageConfigSpec.
func (in *SecureContainerImageConfigSpec) DeepCopy() *SecureContainerImageConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SecureContainerImageConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureContainerImageConfigStatus) DeepCopyInto(out *SecureContainerImageConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureContainerImageConfigStatus.
func (in *SecureContainerImageConfigStatus) DeepCopy() *SecureContainerImageConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SecureContainerImageConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureContainerImageList) DeepCopyInto(out *SecureContainerImageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecureContainerImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureContainerImageList.
func (in *SecureContainerImageList) DeepCopy() *SecureContainerImageList {
	if in == nil {
		return nil
	}
	out := new(SecureContainerImageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecureContainerImageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureContainerImageRef) DeepCopyInto(out *SecureContainerImageRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureContainerImageRef.
func (in *SecureContainerImageRef) DeepCopy() *SecureContainerImageRef {
	if in == nil {
		return nil
	}
	out := new(SecureContainerImageRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureContainerImageSpec) DeepCopyInto(out *SecureContainerImageSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	out.SecureContainerImageConfigRef = in.SecureContainerImageConfigRef
	out.SecureContainerImageConfigSpec = in.SecureContainerImageConfigSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureContainerImageSpec.
func (in *SecureContainerImageSpec) DeepCopy() *SecureContainerImageSpec {
	if in == nil {
		return nil
	}
	out := new(SecureContainerImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureContainerImageStatus) DeepCopyInto(out *SecureContainerImageStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureContainerImageStatus.
func (in *SecureContainerImageStatus) DeepCopy() *SecureContainerImageStatus {
	if in == nil {
		return nil
	}
	out := new(SecureContainerImageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureContainerList) DeepCopyInto(out *SecureContainerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecureContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureContainerList.
func (in *SecureContainerList) DeepCopy() *SecureContainerList {
	if in == nil {
		return nil
	}
	out := new(SecureContainerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecureContainerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureContainerSpec) DeepCopyInto(out *SecureContainerSpec) {
	*out = *in
	out.SecureContainerImageRef = in.SecureContainerImageRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureContainerSpec.
func (in *SecureContainerSpec) DeepCopy() *SecureContainerSpec {
	if in == nil {
		return nil
	}
	out := new(SecureContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureContainerStatus) DeepCopyInto(out *SecureContainerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureContainerStatus.
func (in *SecureContainerStatus) DeepCopy() *SecureContainerStatus {
	if in == nil {
		return nil
	}
	out := new(SecureContainerStatus)
	in.DeepCopyInto(out)
	return out
}
